from smo.util import addKeyFieldToValues
from collections import OrderedDict

Solids = OrderedDict((
	('Aluminium6061', {'label' : 'aluminium 6061',
		'refValues' : {
			'density' : 2700
		}
	}),
	('StainlessSteel304', {'label' : 'stainless steel 304', 
		'refValues' : {
			'density' : 7800
		}
	}),
))

addKeyFieldToValues(Solids)

Fluids = OrderedDict((
	("Acetone", "Acetone"),
	("Air", "Air"),
	("Ammonia", "Ammonia"),
	("Argon", "Argon"),
	("Benzene", "Benzene"),
	("IsoButane", "iso-Butane"),
	("n-Butane", "n-Butane"),
	("cis-2-Butene", "cis-2-Butene"),
	("trans-2-Butene", "trans-2-Butene"),
	("IsoButene", "iso-Butene"),
	("1-Butene", "1-Butene"),
	("CarbonDioxide", "Carbon dioxide"),
	("CarbonMonoxide", "Carbon monoxide"),
	("CarbonylSulfide", "Carbonyl sulfide"),
	("n-Decane", "n-Decane"),
	("Deuterium", "Deuterium"),
	("OrthoDeuterium", "ortho-Deuterium"),
	("ParaDeuterium", "para-Deuterium"),
	("DimethylCarbonate", "Dimethyl carbonate"),
	("DimethylEther", "Dimethyl ether"),
	("n-Dodecane", "n-Dodecane"),
	("D4", "D4"),
	("D5", "D5"),
	("D6", "D6"),
	("Ethane", "Ethane"),
	("Ethanol", "Ethanol"),
	("Ethylene", "Ethylene"),
	("EthylBenzene", "Ethyl benzene"),
	("Fluorine", "Fluorine"),
	("Helium", "Helium"),
	("CycloHexane", "cyclo-Hexane"),
	("Isohexane", "iso-Hexane"),
	("n-Hexane", "n-Hexane"),
	("n-Heptane", "n-Heptane"),
	("HFE143m", "HFE143m"),
	("Hydrogen", "normal-Hydrogen"),
	("OrthoHydrogen", "ortho-Hydrogen"),
	("ParaHydrogen", "para-Hydrogen"),
	("HydrogenSulfide", "Hydrogen sulfide"),
	("Krypton", "Krypton"),
	("Methane", "Methane"),
	("Methanol", "Methanol"),
	("MethylLinoleate", "Methyl linoleate"),
	("MethylLinolenate", "Methyl linolenate"),
	("MethylOleate", "Methyl oleate"),
	("MethylPalmitate", "Methyl palmitate"),
	("MethylStearate", "Methyl stearate"),
	("MD2M", "MD2M"),
	("MD3M", "MD3M"),
	("MD4M", "MD4M"),
	("MDM", "MDM"),
	("MM", "MM"),
	("Neon", "Neon"),
	("Nitrogen", "Nitrogen"),
	("NitrousOxide", "Nitrous oxide"),
	("n-Nonane", "n-Nonane"),
	("n-Octane", "n-Octane"),
	("Oxygen", "Oxygen"),
	("Cyclopentane", "cyclo-Pentane"),
	("Isopentane", "iso-Pentane"),
	("n-Pentane", "n-Pentane"),
	("Neopentane", "neo-Pentane"),
	("CycloPropane", "cyclo-Propane"),
	("n-Propane", "n-Propane"),
	("Propylene", "Propylene"),
	("Propyne", "Propyne"),
	("R11", "R11"),
	("R113", "R113"),
	("R114", "R114"),
	("R116", "R116"),
	("R12", "R12"),
	("R123", "R123"),
	("R1233zd(E)", "R1233zd(E)"),
	("R1234yf", "R1234yf"),
	("R1234ze(E)", "R1234ze(E)"),
	("R1234ze(Z)", "R1234ze(Z)"),
	("R124", "R124"),
	("R125", "R125"),
	("R13", "R13"),
	("R134a", "R134a"),
	("R14", "R14"),
	("R141b", "R141b"),
	("R142b", "R142b"),
	("R143a", "R143a"),
	("R152A", "R152A"),
	("R161", "R161"),
	("R161", "R161"),
	("R21", "R21"),
	("R218", "R218"),
	("R22", "R22"),
	("R227EA", "R227EA"),
	("R23", "R23"),
	("R236EA", "R236EA"),
	("R236FA", "R236FA"),
	("R245fa", "R245fa"),
	("R32", "R32"),
	("R365MFC", "R365MFC"),
	("R41", "R41"),
	("RC318", "RC318"),
	("SulfurDioxide", "SulfurDioxide"),
	("SulfurHexafluoride", "SulfurHexafluoride"),
	("Toluene", "Toluene"),
	("n-Undecane", "n-Undecane"),
	("Water", "Water"),
	("Xenon", "Xenon"),
	("m-Xylene", "m-Xylene"),
	("o-Xylene", "o-Xylene"),
	("p-Xylene", "p-Xylene"),
))
