References = \
{
    "Lemmon-IJT-2004": {
        "comment": "Critical enhancement included", 
        "title": "Viscosity and Thermal Conductivity Equations for Nitrogen, Oxygen, Argon, and Air", 
        "timestamp": "2013.04.08", 
        "journal": "International Journal of Thermophysics", 
        "author": "E. W. Lemmon and R. T Jacobsen", 
        "number": "1", 
        "id": "Lemmon-IJT-2004", 
        "volume": "25", 
        "year": "2004", 
        "owner": "Belli", 
        "type": "article", 
        "pages": "21-69"
    }, 
    "Vogel-JPCRD-1998": {
        "note": "5", 
        "title": "Reference Correlation of the Viscosity of Propane", 
        "timestamp": "2013.04.08", 
        "journal": "J. Phys. Chem. Ref. Data", 
        "author": "E. Vogel and C. K{\\\"u}chenmeister and E. Bich and A. Laesecke", 
        "id": "Vogel-JPCRD-1998", 
        "volume": "27", 
        "year": "1998", 
        "owner": "Belli", 
        "type": "article", 
        "pages": "947-970"
    }, 
    "TillnerRoth-IJT-1995": {
        "title": "A Fundamental Equation of State for 1,1-Difluoroethane (HFC-152a)", 
        "timestamp": "2013.04.08", 
        "journal": "Int. J. Thermophys.", 
        "author": "R. Tillner-Roth", 
        "number": "1", 
        "id": "TillnerRoth-IJT-1995", 
        "volume": "16", 
        "year": "1995", 
        "owner": "Belli", 
        "type": "article", 
        "pages": "91-100"
    }, 
    "Lemmon-IJT-2003": {
        "keyword": "EOS", 
        "title": "Pseudo-Pure Fluid Equations of State for the Refrigerant Blends\nR-410A, R-404A, R-507A, and R-407C", 
        "timestamp": "2013.04.08", 
        "journal": "Int. J. Thermophys.", 
        "author": "E.W. Lemmon", 
        "number": "4", 
        "id": "Lemmon-IJT-2003", 
        "volume": "24", 
        "file": ":D\\:\\\\My_Documents\\\\Library\\\\Papers\\\\Lemmon 2003.pdf:PDF", 
        "year": "2003", 
        "owner": "Belli", 
        "type": "article", 
        "pages": "991-1006"
    }, 
    "Pan-FPE-2012": {
        "title": "An equation of state for the thermodynamic properties of 1,1,1,3,3,3-hexafluoropropane\n(HFC-236fa)", 
        "timestamp": "2013.04.10", 
        "journal": "Fluid Phase Equilibria", 
        "author": "Jiang Pan and Xinfang Rui and Xiaodong Zhao and Liming Qiu", 
        "id": "Pan-FPE-2012", 
        "volume": "321", 
        "year": "2012", 
        "owner": "Belli", 
        "type": "article", 
        "pages": "10-16"
    }, 
    "Meng-JCED-2012": {
        "comment": "Erratum: Limits for deltaeta_r sums should be 0-3 and 4-9. The correct\norder of terms based on the original indices are 0,1,7,9,2,3,4,5,6,8", 
        "title": "Experimental Measurement and Modeling of the Viscosity of Dimethyl\nEther", 
        "timestamp": "2013.04.09", 
        "journal": "J. Chem. Eng. Data", 
        "author": "Xianyang Meng and Jianbo Zhang and Jiangtao Wu and Zhigang Liu", 
        "id": "Meng-JCED-2012", 
        "volume": "57", 
        "year": "2012", 
        "owner": "Belli", 
        "type": "article", 
        "pages": "988-993"
    }, 
    "Friend-JPCRD-1991": {
        "title": "Thermophysical Properties of Ethane", 
        "timestamp": "2013.04.08", 
        "journal": "J. Phys. Chem. Ref. Data", 
        "author": "Daniel G. Friend and Hepburn Ingham and James F. Ely", 
        "number": "2", 
        "id": "Friend-JPCRD-1991", 
        "volume": "20", 
        "year": "1991", 
        "owner": "Belli", 
        "type": "article", 
        "pages": "275-347"
    }, 
    "QuinonesCisneros-JPCRD-2012": {
        "title": "Correlation for the Viscosity of Sulfur Hexafluoride (SF6) from\nthe Triple Point to 1000 K and Pressures to 50 MPa", 
        "timestamp": "2013.04.08", 
        "journal": "Journal of Physical and Chemical Reference Data", 
        "author": "S.E. Qui{\\~n}ones-Cisneros and M.L. Huber and U.K. Deiters", 
        "number": "2", 
        "id": "QuinonesCisneros-JPCRD-2012", 
        "volume": "41", 
        "year": "2012", 
        "owner": "Belli", 
        "type": "article", 
        "pages": "023102-1:11"
    }, 
    "Richter-JCED-2011": {
        "title": "Thermodynamic Properties of 2,3,3,3-Tetrafluoroprop-1-ene (R1234yf):\nVapor Pressure and p-rho-T Measurements and an Equation of State", 
        "timestamp": "2013.04.08", 
        "journal": "J. Chem. Eng. Data", 
        "author": "M. Richter and M.O. McLinden and E.W. Lemmon", 
        "id": "Richter-JCED-2011", 
        "volume": "56", 
        "year": "2011", 
        "owner": "Belli", 
        "type": "article", 
        "pages": "3254-3264"
    }, 
    "Assael-JPCRD-2012B": {
        "title": "Reference Correlation of the Thermal Conductivity of Toluene from\nthe Triple Point to 1000 K and up to 1000 MPa", 
        "timestamp": "2013.04.10", 
        "journal": "J. Phys. Chem Ref. Data", 
        "author": "M. J. Assael and S. K. Mylona and M. L. Huber and R. A. Perkins", 
        "number": "2", 
        "id": "Assael-JPCRD-2012B", 
        "volume": "41", 
        "year": "2012", 
        "owner": "Belli", 
        "type": "article", 
        "pages": "023101-1:12"
    }, 
    "Assael-JPCRD-2012A": {
        "title": "Reference Correlation of the Thermal Conductivity of Benzene from\nthe Triple Point to 725 K and up to 500 MPa", 
        "timestamp": "2013.04.10", 
        "journal": "J. Phys. Chem Ref. Data", 
        "author": "M.J. Assael and E. Mihailidou and M.L. Huber and R.A. Perkins", 
        "id": "Assael-JPCRD-2012A", 
        "volume": "41", 
        "year": "2012", 
        "owner": "Belli", 
        "type": "article", 
        "pages": "043102-1:9"
    }, 
    "Zavoico2001": {
        "title": "Solar Power Tower Design Basis Document", 
        "timestamp": "2013.10.23", 
        "author": "Alexis B. Zavoico", 
        "id": "Zavoico2001", 
        "link": "http://prod.sandia.gov/techlib/access-control.cgi/2001/012100.pdf", 
        "year": "2001", 
        "owner": "jowr", 
        "type": "techreport", 
        "institution": "Sandia Labs"
    }, 
    "deVries-ICR-1995": {
        "title": "Thermodynamic Properties of HCFC 124", 
        "timestamp": "2013.05.01", 
        "booktitle": "19th International Congress of Refrigeration, The Hague, The Netherlands", 
        "author": "B. de Vries and R. Tillner-Roth and H.D. Baehr", 
        "id": "deVries-ICR-1995", 
        "year": "1995", 
        "owner": "Belli", 
        "type": "conference", 
        "pages": "582-589"
    }, 
    "QuinonesCisneros-JCED-2012": {
        "title": "Reference Correlation for the Viscosity Surface of Hydrogen Sulfide", 
        "timestamp": "2013.04.14", 
        "journal": "J. Chem. Eng. Data", 
        "author": "Sergio E. Qui{\\~n}ones-Cisneros and Kurt A. G. Schmidt and Binod\nR. Giri and Pierre Blais and Robert A. Marriott", 
        "id": "QuinonesCisneros-JCED-2012", 
        "volume": "57", 
        "year": "2012", 
        "owner": "Belli", 
        "type": "article", 
        "pages": "3014-3018"
    }, 
    "Vesovic-JPCRD-1990": {
        "title": "The Transport Properties of Carbon Dioxide", 
        "timestamp": "2013.04.08", 
        "journal": "J. Phys. Chem. Ref. Data", 
        "author": "V. Vesovic and W.A. Wakeham and G.A. Olchowy and J.V. Sengers and\nJ.T.R. Watson and J. Millat", 
        "id": "Vesovic-JPCRD-1990", 
        "volume": "19", 
        "year": "1990", 
        "owner": "Belli", 
        "type": "article", 
        "pages": "763--808"
    }, 
    "Wagner-JPCRD-2002": {
        "title": "The IAPWS Formulation 1995 for the Thermodynamic Properties of Ordinary\nWater Substance for General and Scientific Use", 
        "timestamp": "2013.04.08", 
        "journal": "J. Phys. Chem. Ref. Data", 
        "author": "W. Wagner and A. Pruss", 
        "id": "Wagner-JPCRD-2002", 
        "volume": "31", 
        "year": "2002", 
        "owner": "Belli", 
        "type": "article", 
        "pages": "387-535"
    }, 
    "Lemmon-RP-2010": {
        "title": "NIST Standard Reference Database 23: Reference Fluid Thermodynamic\nand Transport Properties-REFPROP, Version 9.0", 
        "timestamp": "2011.03.05", 
        "author": "E.W. Lemmon and M.L. Huber and M.O. McLinden", 
        "year": "2010", 
        "owner": "ibell", 
        "type": "misc", 
        "id": "Lemmon-RP-2010"
    }, 
    "Huber-EF-2009": {
        "title": "Model for the Thermodynamic Properties of a Biodiesel Fuel", 
        "timestamp": "2013.04.08", 
        "journal": "Energy \\& Fuels", 
        "author": "Marcia L. Huber and Eric W. Lemmon and Andrei Kazakov and Lisa S.\nOtt and Thomas J. Bruno", 
        "id": "Huber-EF-2009", 
        "volume": "23", 
        "year": "2009", 
        "owner": "Belli", 
        "type": "article", 
        "pages": "3790-3797"
    }, 
    "Huber-EF-2004": {
        "title": "Transport Properties of n-Dodecane", 
        "timestamp": "2013.04.10", 
        "journal": "Energy \\& Fuels", 
        "author": "Marcia L. Huber and Arno Laesecke and Richard Perkins", 
        "id": "Huber-EF-2004", 
        "volume": "18", 
        "year": "2004", 
        "owner": "Belli", 
        "type": "article", 
        "pages": "968-975"
    }, 
    "Assael-JPCRD-2013A": {
        "title": "Reference Correlation of the Thermal Conductivity of Ethanol from\nthe Triple Point to 600 K and up to 245 MPa", 
        "timestamp": "2013.04.28", 
        "journal": "J. Phys. Chem Ref. Data", 
        "author": "M. J. Assael and E. A. Sykioti and M. L. Huber and R. A. Perkins", 
        "number": "2", 
        "id": "Assael-JPCRD-2013A", 
        "volume": "42", 
        "year": "2013", 
        "owner": "Belli", 
        "type": "article", 
        "pages": "023102-1:10"
    }, 
    "Assael-JPCRD-2013B": {
        "title": "Reference Correlation of the Thermal Conductivity of n-Hexane from\nthe Triple Point to 600 K and up to 500 MPa", 
        "timestamp": "2013.04.28", 
        "journal": "J. Phys. Chem Ref. Data", 
        "author": "M. J. Assael and S. K. Mylona and Ch. A. Tsiglifisi and M. L. Huber\nand R. A. Perkins", 
        "number": "1", 
        "id": "Assael-JPCRD-2013B", 
        "volume": "42", 
        "year": "2013", 
        "owner": "Belli", 
        "type": "article", 
        "pages": "013106-1:8"
    }, 
    "Assael-JPCRD-2013C": {
        "title": "Reference Correlation of the Thermal Conductivity of n-Heptane from\nthe Triple Point to 600 K and up to 250 MPa", 
        "timestamp": "2013.04.28", 
        "journal": "J. Phys. Chem Ref. Data", 
        "author": "M. J. Assael and I. Bogdanou and S. K. Mylona and M. L. Huber and\nR. A. Perkins and V. Vesovic", 
        "number": "2", 
        "id": "Assael-JPCRD-2013C", 
        "volume": "42", 
        "year": "2013", 
        "owner": "Belli", 
        "type": "article", 
        "pages": "023101-1:9"
    }, 
    "Thol-2012": {
        "title": "Equation of State for a Refrigerant Mixture of R365mfc (1,1,1,3,3-Pentafluorobutane)\nand Galden HT 55 (Perfluoropolyether)", 
        "timestamp": "2013.08.05", 
        "author": "Monika Thol and Eric W. Lemmon and Roland Span", 
        "note": "Unpublished", 
        "year": "2012", 
        "owner": "Belli", 
        "type": "unpublished", 
        "id": "Thol-2012"
    }, 
    "QuinonesCisneros-FPE-2000": {
        "title": "The friction theory (f-theory) for viscosity modeling", 
        "timestamp": "2013.07.07", 
        "journal": "Fluid Phase Equilibria", 
        "author": "Sergio E. Qui{\\~n}ones-Cisneros and Claus K. Zeberg-Mikkelsen and\nErling H. Stenby", 
        "id": "QuinonesCisneros-FPE-2000", 
        "volume": "169", 
        "year": "2000", 
        "owner": "Belli", 
        "type": "article", 
        "pages": "249-276"
    }, 
    "QuinonesCisneros-FPE-2001": {
        "title": "One parameter friction theory models for viscosity", 
        "timestamp": "2013.07.07", 
        "journal": "Fluid Phase Equilibria", 
        "author": "Sergio E. Qui{\\~n}ones-Cisneros and Claus K. Z{\\'e}berg-Mikkelsen\nand Erling H. Stenby", 
        "id": "QuinonesCisneros-FPE-2001", 
        "volume": "176", 
        "year": "2001", 
        "owner": "Belli", 
        "type": "article", 
        "pages": "1-16"
    }, 
    "Huber-FPE-1992": {
        "title": "Prediction of Viscosity of Refrigerants and Refrigerant Mixtures", 
        "timestamp": "2013.05.29", 
        "journal": "Fluid Phase Equilibria", 
        "author": "Marcia L. Huber and James F. Ely", 
        "id": "Huber-FPE-1992", 
        "volume": "80", 
        "year": "1992", 
        "owner": "Belli", 
        "type": "article", 
        "pages": "239-248"
    }, 
    "Michailidou-JPCRD-2013": {
        "title": "Reference Correlation of the Viscosity of n-Hexane from the Triple\nPoint to 600 K and up to 100 MPa", 
        "timestamp": "2013.09.21", 
        "journal": "J. Phys. Chem. Ref. Data", 
        "author": "E. K. Michailidou and M. J. Assael and M. L. Huber and R. A. Perkins", 
        "number": "3", 
        "id": "Michailidou-JPCRD-2013", 
        "volume": "42", 
        "year": "2013", 
        "owner": "Belli", 
        "type": "article", 
        "pages": "033104:1-12"
    }, 
    "Vogel-HTHP-1999": {
        "title": "Viscosity for n-Butane in the Fluid Region", 
        "timestamp": "2013.04.08", 
        "journal": "High Temp. - High Pressures", 
        "author": "E. Vogel and C. Kuechenmeister and E. Bich", 
        "number": "2", 
        "id": "Vogel-HTHP-1999", 
        "volume": "31", 
        "year": "1999", 
        "owner": "Belli", 
        "type": "article", 
        "pages": "173-186"
    }, 
    "Leachman-JPCRD-2009": {
        "title": "Fundamental Equations of State for Parahydrogen, Normal Hydrogen, and Orthohydrogen", 
        "timestamp": "2013.04.09", 
        "journal": "J. Phys. Chem. Ref. Data", 
        "author": "J.W. Leachman and R.T. Jacobsen and S.G. Penoncello and E.W. Lemmon", 
        "number": "3", 
        "id": "Leachman-JPCRD-2009", 
        "volume": "38", 
        "year": "2009", 
        "owner": "Belli", 
        "type": "article", 
        "pages": "721-748"
    }, 
    "Guder-JPCRD-2009": {
        "title": "A Reference Equation of State for the Thermodynamic Properties of\nSulfur Hexafluoride SF6 for Temperatures from the Melting Line to\n625 K and Pressures up to 150 MPa", 
        "timestamp": "2013.04.08", 
        "journal": "J. Phys. Chem. Ref. Data", 
        "author": "C. Guder and W. Wagner", 
        "number": "1", 
        "id": "Guder-JPCRD-2009", 
        "volume": "38", 
        "year": "2009", 
        "owner": "Belli", 
        "type": "article", 
        "pages": "33-94"
    }, 
    "Laesecke-IJR-1996": {
        "title": "An improved correlation for the thermal conductivity of HCFC123\n(2,2-dichloro-1,1,1-trifluoroethane)", 
        "timestamp": "2013.04.13", 
        "journal": "Int J. Refrig.", 
        "author": "Arno Laesecke and Richard A. Perkins and John B. Howley", 
        "number": "4", 
        "id": "Laesecke-IJR-1996", 
        "volume": "19", 
        "year": "1996", 
        "owner": "Belli", 
        "type": "article", 
        "pages": "231-238"
    }, 
    "Mulero-JPCRD-2012": {
        "title": "Recommended Correlations for the Surface Tension of Common Fluids", 
        "timestamp": "2013.04.08", 
        "journal": "J. Phys. Chem. Ref. Data", 
        "author": "A. Mulero and I. Cachadi{\\~n}a and M. I. Parra", 
        "number": "4", 
        "id": "Mulero-JPCRD-2012", 
        "volume": "41", 
        "year": "2012", 
        "owner": "Belli", 
        "type": "article", 
        "pages": "043105-1:13"
    }, 
    "Poling-BOOK-2001": {
        "publisher": "McGraw Hill", 
        "author": "Bruce E. Poling and John M. Prausnitz and John P. O'Connell", 
        "timestamp": "2013.04.08", 
        "title": "The Properties of Gases and Liquids, 5th edition", 
        "year": "2001", 
        "owner": "Belli", 
        "type": "book", 
        "id": "Poling-BOOK-2001"
    }, 
    "Kunz-BOOK-2007": {
        "publisher": "VDI Verlag GmbH", 
        "author": "O. Kunz and R. Klimeck and W. Wagner and M. Jaeschke", 
        "timestamp": "2013.07.07", 
        "title": "The GERG-2004 Wide-Range Equation of State for Natural Gases and\nOther Mixtures", 
        "year": "2007", 
        "owner": "Belli", 
        "type": "book", 
        "id": "Kunz-BOOK-2007"
    }, 
    "Lemmon-PROPYLENE-2013": {
        "title": "Equation of state for propylene", 
        "timestamp": "2013.04.10", 
        "author": "E.W. Lemmon and U. Overhoff and M.O. McLinden and W. Wagner", 
        "note": "Personal communication with Eric Lemmon", 
        "year": "2010", 
        "owner": "Belli", 
        "type": "unpublished", 
        "id": "Lemmon-PROPYLENE-2013"
    }, 
    "Colonna-FPE-2006": {
        "title": "Multiparameter equations of state for selected siloxanes", 
        "timestamp": "2013.04.08", 
        "journal": "Fluid Phase Equilibria", 
        "author": "P. Colonna and N.R. Nannan and A. Guardone and E.W. Lemmon", 
        "id": "Colonna-FPE-2006", 
        "volume": "244", 
        "year": "2006", 
        "owner": "Belli", 
        "type": "article", 
        "pages": "193-211"
    }, 
    "Colonna-FPE-2008": {
        "title": "Multiparameter equations of state for siloxanes: [(CH3)3-Si-O1/2]2-[O-Si-(CH3)2]i=1,...,3, and [O-Si-(CH3)2]6", 
        "timestamp": "2013.04.08", 
        "journal": "Fluid Phase Equilibria", 
        "author": "P. Colonna and N.R. Nannan and A. Guardone", 
        "id": "Colonna-FPE-2008", 
        "volume": "263", 
        "year": "2008", 
        "owner": "Belli", 
        "type": "article", 
        "pages": "115-130"
    }, 
    "Patek2006": {
        "doi": "10.1016/j.ijrefrig.2005.10.007", 
        "title": "A computationally effective formulation of the thermodynamic properties\nof LiBr-H2O solutions from 273 to 500 K over full composition range", 
        "timestamp": "2013.11.22", 
        "journal": "International Journal of Refrigeration", 
        "author": "J. P\\'atek and J. Klomfar", 
        "number": "4", 
        "month": "June", 
        "volume": "29", 
        "id": "Patek2006", 
        "year": "2006", 
        "owner": "jowr", 
        "type": "article", 
        "pages": "566--578"
    }, 
    "Piazza-FPE-2013": {
        "title": "An equation of state for methanol including the association term\nof SAFT", 
        "timestamp": "2014.02.02", 
        "journal": "Fluid Phase Equilibria", 
        "author": "L. Piazza and R. Span", 
        "id": "Piazza-FPE-2013", 
        "volume": "349", 
        "year": "2013", 
        "owner": "Belli", 
        "type": "article", 
        "pages": "12-24"
    }, 
    "Akasaka-IJR-2012": {
        "title": "A fundamental equation of state for trifluoromethyl methyl ether\n(HFE-143m) and its application to refrigeration cycle analysis", 
        "timestamp": "2013.04.10", 
        "journal": "International Journal of Refrigeration", 
        "author": "Ryo Akasaka and Yohei Kayukawa", 
        "id": "Akasaka-IJR-2012", 
        "volume": "35", 
        "year": "2012", 
        "owner": "Belli", 
        "type": "article", 
        "pages": "1003-1013"
    }, 
    "Lemmon-FPE-2005": {
        "title": "Thermodynamic properties of the butenes Part II. Short fundamental\nequations of state", 
        "timestamp": "2013.04.08", 
        "journal": "Fluid Phase Equilibria", 
        "author": "Eric W. Lemmon and E. Christian Ihmels", 
        "id": "Lemmon-FPE-2005", 
        "volume": "228-229", 
        "year": "2005", 
        "owner": "Belli", 
        "type": "article", 
        "pages": "173-187"
    }, 
    "McLinden-IJR-2000": {
        "title": "An extended corresponding states model for the thermal conductivity\nof refrigerants and refrigerant mixtures", 
        "timestamp": "2010.07.06", 
        "journal": "Int. J. Refrig.", 
        "author": "Mark O. McLinden and Sanford A. Klein and Richard A. Perkins", 
        "id": "McLinden-IJR-2000", 
        "volume": "23", 
        "year": "2000", 
        "owner": "ibell", 
        "type": "article", 
        "pages": "43-63"
    }, 
    "Schroeder-MSTHESIS-2011": {
        "school": "University of Idaho", 
        "title": "A New Fundamental Equation for Ethanol", 
        "timestamp": "2013.04.13", 
        "author": "Jacob Armin Schroeder", 
        "year": "2011", 
        "owner": "Belli", 
        "type": "mastersthesis", 
        "id": "Schroeder-MSTHESIS-2011"
    }, 
    "Froeba-2000": {
        "note": "10.1023/A:1006689724974", 
        "issn": "0195-928X", 
        "type": "article", 
        "keyword": "Physics and Astronomy", 
        "title": "Saturated Liquid Viscosity and Surface Tension of Alternative Refrigerants", 
        "timestamp": "2011.04.17", 
        "journal": "Int. J. Thermophys.", 
        "author": "A.P. Fr\\\"{o}ba and S. Will and A. Leipertz", 
        "publisher": "Springer Netherlands", 
        "id": "Froeba-2000", 
        "volume": "21", 
        "link": "http://dx.doi.org/10.1023/A:1006689724974", 
        "year": "2000", 
        "owner": "ibell", 
        "issue": "6", 
        "pages": "1225-1253"
    }, 
    "Katti-ACE-1986": {
        "title": "Thermodynamic Properties of Neon for Temperatures from the Triple\nPoint to 700 K at Pressures to 700 MPa", 
        "timestamp": "2013.04.30", 
        "journal": "Advances in Cryogenic Engineering", 
        "author": "R. Katti and R.T. Jacobsen and R.B. Stewart and M. Jehangiri", 
        "id": "Katti-ACE-1986", 
        "volume": "31", 
        "year": "1986", 
        "owner": "Belli", 
        "type": "article", 
        "pages": "1189-1197"
    }, 
    "Geller-IJT-2001": {
        "title": "Thermal Conductivity of the Refrigerant mixtures R404A, R407C, R410A, and R507A", 
        "timestamp": "2010.06.30", 
        "journal": "Int. J. Thermophys.", 
        "author": "V.Z. Geller and B.Z. Nemzer and U.V. Cheremnykh", 
        "id": "Geller-IJT-2001", 
        "volume": "22", 
        "year": "2001", 
        "owner": "ibell", 
        "type": "article", 
        "pages": "1034-1043"
    }, 
    "Heide-IJR-1997": {
        "title": "The surface tension of HFC refrigerants and mixtures", 
        "timestamp": "2013.04.08", 
        "journal": "Int J. Refrig.", 
        "author": "R. Heide", 
        "id": "Heide-IJR-1997", 
        "volume": "20", 
        "year": "1997", 
        "owner": "Belli", 
        "type": "article", 
        "pages": "496-503"
    }, 
    "TillnerRoth-JPCRD-1997": {
        "title": "An international standard equation of state for difluoromethane\n(R-32) for temperatures from the triple point at 136.34 K to 435\nK and pressures up to 70 MPa", 
        "timestamp": "2013.04.08", 
        "journal": "J. Phys. Chem. Ref. Data", 
        "author": "R. Tillner-Roth and A. Yokozeki", 
        "number": "6", 
        "id": "TillnerRoth-JPCRD-1997", 
        "volume": "26", 
        "year": "1997", 
        "owner": "Belli", 
        "type": "article", 
        "pages": "1273-1328"
    }, 
    "McLinden-PURDUE-2010": {
        "comment": "The constants as written in the paper are not the most up-to-date\nEOS constants. REFPROP 9.1 contains the updated coefficients and\nthey are used with permission. Also the sign of the terms for eta_k\nand beta_k should be inverted in the table", 
        "title": "Thermodynamic Properties of trans-1,3,3,3-tetrafluoropropene [R1234ze(E)]:\nMeasurements of Density and Vapor Pressure and a Comprehensive Equation\nof State", 
        "timestamp": "2013.04.08", 
        "booktitle": "International Refrigeration and Air Conditioning Conference at Purdue, July 12-15, 2010", 
        "author": "Mark O. McLinden and Monika Thol and Eric W. Lemmon", 
        "year": "2010", 
        "owner": "Belli", 
        "type": "conference", 
        "id": "McLinden-PURDUE-2010"
    }, 
    "Thol-HTHP-2012": {
        "title": "Equation of state for benzene for temperatures from the melting\nline up to 725 K with pressures up to 500 MPa", 
        "timestamp": "2013.04.10", 
        "journal": "High Temperatures-High Pressures", 
        "author": "M. Thol and E.W. Lemmon and R. Span", 
        "id": "Thol-HTHP-2012", 
        "volume": "41", 
        "year": "2012", 
        "owner": "Belli", 
        "type": "article", 
        "pages": "81-97"
    }, 
    "deReuck-BOOK-1993": {
        "publisher": "Blackwell Scientific Publications", 
        "author": "K.M. de Reuck and R.J.B. Craven", 
        "timestamp": "2013.05.17", 
        "title": "Methanol: International Thermodynamic Tables of the Fluid State\n- 12", 
        "year": "1993", 
        "owner": "Belli", 
        "type": "book", 
        "id": "deReuck-BOOK-1993"
    }, 
    "deReuck-BOOK-1990": {
        "publisher": "Blackwell Scientific Publications", 
        "author": "K.M. de Reuck", 
        "timestamp": "2013.05.17", 
        "title": "Fluorine: International Thermodynamic Tables of the Fluid State\n- 11", 
        "year": "1990", 
        "owner": "Belli", 
        "type": "book", 
        "id": "deReuck-BOOK-1990"
    }, 
    "Setzmann-JPCRD-1991": {
        "title": "A New Equation of State and Tables of Thermodynamic Properties for\nMethane Covering the Range from the Melting Line to 625 K at Pressures\nup to 1000 MPa", 
        "timestamp": "2013.04.08", 
        "journal": "J. Phys. Chem. Ref. Data", 
        "author": "U. Setzmann and W. Wagner", 
        "number": "6", 
        "id": "Setzmann-JPCRD-1991", 
        "volume": "20", 
        "year": "1991", 
        "owner": "Belli", 
        "type": "article", 
        "pages": "1061-1151"
    }, 
    "Zhou-JPCRD-2011": {
        "title": "Thermodynamic Properties of Dimethyl Carbonate", 
        "timestamp": "2013.04.09", 
        "journal": "J. Phys. Chem. Ref. Data", 
        "author": "Yong Zhou and Jiangtao Wu and Eric W. Lemmon", 
        "number": "4", 
        "id": "Zhou-JPCRD-2011", 
        "volume": "40", 
        "year": "2011", 
        "owner": "Belli", 
        "type": "article", 
        "pages": "043106-1:11"
    }, 
    "Zhou-JPCRD-2012": {
        "title": "Thermodynamic Properties of o-Xylene, m-Xylene, p-Xylene, and Ethylbenzene", 
        "timestamp": "2013.04.08", 
        "journal": "J. Phys. Chem. Ref. Data", 
        "author": "Yong Zhou and Jiangtao Wu and Eric W. Lemmon", 
        "number": "2", 
        "id": "Zhou-JPCRD-2012", 
        "volume": "41", 
        "year": "2012", 
        "owner": "Belli", 
        "type": "article", 
        "pages": "023103-1 -- 023103-26"
    }, 
    "Span-JPCRD-1996": {
        "title": "A New Equation of State for Carbon Dioxide Covering the Fluid Region\nfrom the Triple Point Temperature to 1100 K at Pressures up to 800\nMPa", 
        "timestamp": "2013.04.08", 
        "journal": "J. Phys. Chem. Ref. Data", 
        "author": "R. Span and W. Wagner", 
        "id": "Span-JPCRD-1996", 
        "volume": "25", 
        "year": "1996", 
        "owner": "Belli", 
        "type": "article", 
        "pages": "1509-1596"
    }, 
    "Lemmon-EF-2004": {
        "title": "Thermodynamic Properties of n-Dodecane", 
        "timestamp": "2013.04.09", 
        "journal": "Energy \\& Fuels", 
        "author": "Eric W. Lemmon and Marcia L. Huber", 
        "id": "Lemmon-EF-2004", 
        "volume": "18", 
        "year": "2004", 
        "owner": "Belli", 
        "type": "article", 
        "pages": "960-967"
    }, 
    "Thorade-EES-2013": {
        "doi": "10.1007/s12665-013-2394-z", 
        "keyword": "defined by specifying any,energy \\'{a} partial derivatives,in fluid\ncycle,nation of two independent,other combi-,state can also be,state\nproperties,thermodynamic properties \\'{a} helmholtz,\\'{a} dynamic\nsimulation", 
        "title": "Partial derivatives of thermodynamic state properties for dynamic\nsimulation", 
        "timestamp": "2013.05.01", 
        "journal": "Environmental Earth Sciences", 
        "author": "Thorade, Matthis and Saadat, Ali", 
        "month": "apr", 
        "link": "http://link.springer.com/10.1007/s12665-013-2394-z", 
        "year": "2013", 
        "owner": "jowr", 
        "type": "article", 
        "id": "Thorade-EES-2013", 
        "issn": "1866-6280"
    }, 
    "Assael-JPCRD-2011": {
        "title": "Correlation of the Thermal Conductivity of Normal and Parahydrogen\nfrom the Triple Point to 1000 K and up to 100 MPa", 
        "timestamp": "2013.04.09", 
        "journal": "J. Phys. Chem. Ref. Data", 
        "author": "M. J. Assael and J.-A. M. Assael and M. L. Huber and R. A. Perkins\nand Y. Takata", 
        "number": "3", 
        "id": "Assael-JPCRD-2011", 
        "volume": "40", 
        "year": "2011", 
        "owner": "Belli", 
        "type": "article", 
        "pages": "033101-1:13"
    }, 
    "Assael-JPCRD-2012": {
        "title": "Reference Correlation of the Thermal Conductivity of Sulfur Hexafluoride\nfrom the Triple Point to 1000 K and up to 150 MPa", 
        "timestamp": "2013.04.08", 
        "journal": "Journal of Physical and Chemical Reference Data", 
        "author": "M. J. Assael and I. A. Koini and K. D. Antoniadis and M. L. Huber\nand I. M. Abdulagatov and R. A. Perkins", 
        "number": "2", 
        "id": "Assael-JPCRD-2012", 
        "volume": "41", 
        "year": "2012", 
        "owner": "Belli", 
        "type": "article", 
        "pages": "023104-1:9"
    }, 
    "Polt-CT-1992": {
        "title": "Parameter der thermischen Zustandsgleichung von Bender f{\\\"u} 14\nmehratomige reine Stoffe", 
        "timestamp": "2013.04.29", 
        "journal": "Chem. Technik", 
        "author": "Axel Polt and Bernhard Platzer and Gerd Maurer", 
        "id": "Polt-CT-1992", 
        "volume": "22", 
        "year": "1992", 
        "owner": "Belli", 
        "type": "article", 
        "pages": "216-224"
    }, 
    "Buecker-JPCRD-2006": {
        "title": "A Reference Equation of State for the Thermodynamic Properties of\nEthane for Temperatures from the Melting Line to 675 K and Pressures\nup to 900 MPa", 
        "timestamp": "2013.04.08", 
        "journal": "J. Phys. Chem. Ref. Data", 
        "author": "D. Buecker and W. Wagner", 
        "number": "1", 
        "id": "Buecker-JPCRD-2006", 
        "volume": "35", 
        "year": "2006", 
        "owner": "Belli", 
        "type": "article", 
        "pages": "205-266"
    }, 
    "Tegeler-JPCRD-1999": {
        "title": "A New Equation of State for Argon Covering the Fluid Region for\nTemperatures From the Melting Line to 700 K at Pressures up to 1000\nMPa", 
        "timestamp": "2013.04.08", 
        "journal": "J. Phys. Chem. Ref. Data", 
        "author": "Ch. Tegeler and R. Span and W. Wagner", 
        "id": "Tegeler-JPCRD-1999", 
        "volume": "28", 
        "year": "1999", 
        "owner": "Belli", 
        "type": "article", 
        "pages": "779-850"
    }, 
    "Shan-ASHRAE-2000": {
        "title": "A Generalized Model for Viscosity and Thermal Conductivity of Trifluoromethane\n(R-23)", 
        "timestamp": "2013.04.29", 
        "journal": "ASHRAE Transactions", 
        "author": "Zhengjun Shan and Steven G. Penoncello and Richard T. Jacobsen", 
        "id": "Shan-ASHRAE-2000", 
        "year": "2000", 
        "owner": "Belli", 
        "type": "article", 
        "pages": "DA-00-10-2"
    }, 
    "TillnerRoth-DKV-1993": {
        "title": "Eine neue Fundamentalgleichung fur Ammoniak (A new Fundamental Equation\nof State for Ammonia)", 
        "timestamp": "2013.04.08", 
        "booktitle": "Deutscher Kaelte- und Klimatechnischer Verein Tagung 1993", 
        "author": "R. Tillner-Roth and F. Harms-Watzenberg and H.D. Baehr", 
        "id": "TillnerRoth-DKV-1993", 
        "year": "1993", 
        "owner": "Belli", 
        "type": "conference", 
        "journal": "Deutscher Kaelte- und Klimatechnischer Verein Tagung 1993"
    }, 
    "Gedanitz-PREPRINT-2013": {
        "title": "Speed of sound measurements and a fundamental equation of state\nfor cyclopentane", 
        "timestamp": "2013.04.10", 
        "author": "Holger Gedanitz and Mar{\\'i}a J. D{\\'a}vila and Eric W. Lemmon", 
        "year": "To be published, preprint provided by Eric Lemmon", 
        "owner": "Belli", 
        "type": "article", 
        "id": "Gedanitz-PREPRINT-2013"
    }, 
    "Kunz-JCED-2012": {
        "title": "The GERG-2008 Wide-Range Equation of State for Natural Gases and\nOther Mixtures: An Expansion of GERG-2004", 
        "timestamp": "2013.07.07", 
        "journal": "Journal of Chemical and Engineering Data", 
        "author": "O. Kunz and W. Wagner", 
        "id": "Kunz-JCED-2012", 
        "volume": "57", 
        "year": "2012", 
        "owner": "Belli", 
        "type": "article", 
        "pages": "3032-3091"
    }, 
    "Melinder-BOOK-2010": {
        "publisher": "IIF-IIR Publishing", 
        "author": "{\\r{A}}ke Melinder", 
        "title": "Properties of Secondary Working Fluids for Indirect Systems", 
        "year": "2010", 
        "type": "book", 
        "id": "Melinder-BOOK-2010"
    }, 
    "Kiselev-IECR-2005": {
        "title": "Generalized SAFT-DFT/DMT Model for the Thermodynamic, Interfacial, and Transport Properties of Associating Fluids: Application for n-Alkanols", 
        "timestamp": "2013.04.14", 
        "journal": "Ind. Eng. Chem. Res.", 
        "author": "S. B. Kiselev and J. F. Ely and I. M. Abdulagatov and M. L. Huber", 
        "id": "Kiselev-IECR-2005", 
        "volume": "44", 
        "year": "2005", 
        "owner": "Belli", 
        "type": "article", 
        "pages": "6916-6927"
    }, 
    "Perkins-JCED-2002B": {
        "title": "Measurement and Correlation of the Thermal Conductivity of Isobutane\nfrom 114 K to 600 K at Pressures to 70 MPa", 
        "timestamp": "2013.04.08", 
        "journal": "J. Chem. Eng. Data", 
        "author": "R.A. Perkins", 
        "number": "5", 
        "id": "Perkins-JCED-2002B", 
        "volume": "47", 
        "year": "2002", 
        "owner": "Belli", 
        "type": "article", 
        "pages": "1272-1279"
    }, 
    "Perkins-JCED-2002A": {
        "title": "Measurement and Correlation of the Thermal Conductivity of Butane\nfrom 135 K to 600 K at Pressures to 70 MPa", 
        "timestamp": "2013.04.08", 
        "journal": "J. Chem. Eng. Data", 
        "author": "R.A. Perkins and M.L.V. Ramires and C.A. Nieto de Castro and L. Cusco", 
        "number": "5", 
        "id": "Perkins-JCED-2002A", 
        "volume": "47", 
        "year": "2002.", 
        "owner": "Belli", 
        "type": "article", 
        "pages": "1263-1271"
    }, 
    "LemmonJacobsen-JPCRD-2000": {
        "title": "An International Standard Formulation for the Thermodynamic Properties\nof 1,1,1-Trifluoroethane (HFC-143a) for Temperatures From 161 to\n450 K and Pressures to 50 MPa", 
        "timestamp": "2013.04.09", 
        "journal": "J. Phys. Chem. Ref. Data", 
        "author": "Eric W. Lemmon and Richard T. Jacobsen", 
        "number": "4", 
        "id": "LemmonJacobsen-JPCRD-2000", 
        "volume": "29", 
        "year": "2000", 
        "owner": "Belli", 
        "type": "article", 
        "pages": "521-552"
    }, 
    "Lemmon-JCED-2006": {
        "title": "Short Fundamental Equations of State for 20 Industrial Fluids", 
        "timestamp": "2013.04.08", 
        "journal": "J. Chem. Eng. Data", 
        "author": "E.W. Lemmon and R. Span", 
        "id": "Lemmon-JCED-2006", 
        "volume": "51", 
        "year": "2006", 
        "owner": "Belli", 
        "type": "article", 
        "pages": "785-850"
    }, 
    "Span-IJT-2003B": {
        "title": "Equations of State for Technical Applications. II. Results for Nonpolar\nFluids", 
        "timestamp": "2013.04.08", 
        "journal": "International Journal of Thermophysics", 
        "author": "R. Span and W. Wagner", 
        "id": "Span-IJT-2003B", 
        "volume": "24", 
        "year": "2003", 
        "owner": "Belli", 
        "type": "article", 
        "pages": "41-109"
    }, 
    "Span-IJT-2003C": {
        "title": "Equations of State for Technical Applications. III. Results for\nPolar Fluids", 
        "timestamp": "2013.04.08", 
        "journal": "International Journal of Thermophysics", 
        "author": "R. Span and W. Wagner", 
        "id": "Span-IJT-2003C", 
        "volume": "24", 
        "year": "2003", 
        "owner": "Belli", 
        "type": "article", 
        "pages": "111-162"
    }, 
    "Huber-JPCRD-2012": {
        "title": "New International Formulation for the Thermal Conductivity of H2O", 
        "timestamp": "2013.04.08", 
        "journal": "J. Phys. Chem Ref. Data", 
        "author": "M. L. Huber and R. A. Perkins and D. G. Friend and J. V. Sengers\nand M. J. Assael and I. N. Metaxa and K. Miyagawa and R. Hellmann\nand E. Vogel", 
        "number": "3", 
        "id": "Huber-JPCRD-2012", 
        "volume": "41", 
        "year": "2012", 
        "owner": "Belli", 
        "type": "article", 
        "pages": "033102-1:23"
    }, 
    "Vogel-IJT-2000": {
        "title": "Viscosity Correlation for Isobutane over Wide Ranges of the Fluid\nRegion", 
        "timestamp": "2013.04.08", 
        "journal": "Int. J. Thermophys", 
        "author": "E. Vogel and C. Kuechenmeister and E. Bich", 
        "number": "2", 
        "id": "Vogel-IJT-2000", 
        "volume": "21", 
        "year": "2000", 
        "owner": "Belli", 
        "type": "article", 
        "pages": "343-356"
    }, 
    "Peng-IECF-1976": {
        "title": "A New Two-Constant Equation of State", 
        "timestamp": "2013.07.07", 
        "journal": "Ind. Eng. Chem. Fundamen.", 
        "author": "Ding-Yu Peng and Donald B. Robinson", 
        "number": "1", 
        "id": "Peng-IECF-1976", 
        "volume": "15", 
        "year": "1976", 
        "owner": "Belli", 
        "type": "article", 
        "pages": "59-64"
    }, 
    "Lemmon-JCED-2009": {
        "title": "Thermodynamic Properties of Propane. III. A Reference Equation of\nState for Temperatures from the Melting Line to 650 K and Pressures\nup to 1000 MPa", 
        "timestamp": "2013.03.19", 
        "journal": "Journal of Chemical Engineering Data", 
        "author": "Eric W. Lemmon and Mark O. McLinden and Wolfgang Wagner", 
        "id": "Lemmon-JCED-2009", 
        "volume": "54", 
        "year": "2009", 
        "owner": "Belli", 
        "type": "article", 
        "pages": "3141-3180"
    }, 
    "Krauss-IJT-1996": {
        "title": "Transport Properties of 1,1-Difluoroethane (R152a)", 
        "timestamp": "2013.04.28", 
        "journal": "Int. J. Thermophys", 
        "author": "R. Krauss and I V. C. Weiss and T. A. Edison and J. V. Sengers and\nK. Stephan", 
        "id": "Krauss-IJT-1996", 
        "volume": "17", 
        "year": "1996", 
        "owner": "Belli", 
        "type": "article", 
        "pages": "731-757"
    }, 
    "TillnerRoth-JPCRD-1994": {
        "title": "A International Standard Formulation for the Thermodynamic Properties\nof 1,1,1,2-Tetrafluoroethane (HFC-134a) for Temperatures from 170\nK to 455 K and Pressures up to 70 MPa", 
        "timestamp": "2013.04.08", 
        "journal": "J. Phys. Chem. Ref. Data", 
        "author": "Reiner Tillner-Roth and Hans Dieter Baehr", 
        "id": "TillnerRoth-JPCRD-1994", 
        "volume": "23", 
        "year": "1994", 
        "owner": "Belli", 
        "type": "article", 
        "pages": "657-729"
    }, 
    "Llovell-JPCB-2013": {
        "title": "Transport Properties of Mixtures by the Soft-SAFT + Free-Volume\nTheory: Application to Mixtures of n-Alkanes and Hydrofluorocarbons", 
        "timestamp": "2013.07.07", 
        "journal": "Journal of Physical Chemistry B", 
        "author": "F. Llovell and R. M. Marcos and L. F. Vega", 
        "id": "Llovell-JPCB-2013", 
        "volume": "117", 
        "year": "2013", 
        "owner": "Belli", 
        "type": "article", 
        "pages": "5195-5205"
    }, 
    "Lemmon-JPCRD-2004": {
        "title": "Equations of State for Mixtures of R-32, R-125, R-134a, R-143a, and R-152a", 
        "timestamp": "2013.07.07", 
        "journal": "J. Phys. Chem. Ref. Data", 
        "author": "Eric W. Lemmon and Richard T. Jacobsen", 
        "number": "2", 
        "id": "Lemmon-JPCRD-2004", 
        "volume": "33", 
        "year": "2004", 
        "owner": "Belli", 
        "type": "article", 
        "pages": "593-620"
    }, 
    "Lemmon-JPCRD-2005": {
        "title": "A New Functional Form and New Fitting Techniques for Equations of\nState with Application to Pentafluoroethane (HFC-125)", 
        "timestamp": "2013.04.13", 
        "journal": "J. Phys. Chem. Ref. Data", 
        "author": "Eric W. Lemmon and Richard T Jacobsen", 
        "number": "1", 
        "id": "Lemmon-JPCRD-2005", 
        "volume": "34", 
        "year": "2005", 
        "owner": "Belli", 
        "type": "article", 
        "pages": "69-108"
    }, 
    "Allal-PRE-2001": {
        "title": "Free-volume viscosity model for fluids in the dense and gaseous\nstates", 
        "timestamp": "2013.07.07", 
        "journal": "Physical Review E", 
        "author": "A. Allal and C. Boned and A. Baylaucq", 
        "id": "Allal-PRE-2001", 
        "volume": "64", 
        "year": "2001", 
        "owner": "Belli", 
        "type": "article", 
        "pages": "011203-1:10"
    }, 
    "Hands-CRYO-1981": {
        "title": "A Correlation of Thermal Conductivity Data for Helium", 
        "timestamp": "2013.08.05", 
        "journal": "Cryogenics", 
        "author": "B.A. Hands and V.D. Arp", 
        "number": "12", 
        "id": "Hands-CRYO-1981", 
        "volume": "21", 
        "year": "1981", 
        "owner": "Belli", 
        "type": "article", 
        "pages": "697-703"
    }, 
    "Kamei-IJT-1995": {
        "title": "Application of Nonlinear Regression in the Development of a Wide\nRange Formulation for HCFC-22", 
        "timestamp": "2013.04.08", 
        "journal": "International Journal of Thermophysics", 
        "author": "A. Kamei and S. W. Beyerlein and R. T Jacobsen", 
        "number": "5", 
        "id": "Kamei-IJT-1995", 
        "volume": "16", 
        "year": "1995", 
        "owner": "Belli", 
        "type": "article", 
        "pages": "1155-1164"
    }, 
    "Stewart-JPCRD-1991": {
        "title": "Thermodynamic Properties of Oxygen from the Triple Point to 300\nK with Pressures to 80 MPa", 
        "timestamp": "2013.04.08", 
        "journal": "J. Phys. Chem. Ref. Data", 
        "author": "Richard B. Stewart and Richard T. Jacobsen and W. Wagner", 
        "number": "5", 
        "id": "Stewart-JPCRD-1991", 
        "volume": "20", 
        "year": "1991", 
        "owner": "Belli", 
        "type": "article", 
        "pages": "917-1021"
    }, 
    "Buecker-JPCRD-2006B": {
        "title": "Reference Equations of State for the Thermodynamic Properties of\nFluid Phase n-Butane and Isobutane", 
        "timestamp": "2013.04.30", 
        "journal": "J. Phys. Chem. Ref. Data", 
        "author": "D. Buecker and W. Wagner", 
        "number": "2", 
        "id": "Buecker-JPCRD-2006B", 
        "volume": "35", 
        "year": "2006", 
        "owner": "Belli", 
        "type": "article", 
        "pages": "929-1019"
    }, 
    "Perkins-JCED-2006": {
        "title": "Measurement and Correlation of the Thermal Conductivity of Pentafluoroethane\n(R125) from 190 K to 512 K at Pressures to 70 MPa", 
        "timestamp": "2013.04.13", 
        "journal": "J. Chem. Eng. Data", 
        "author": "Richard A. Perkins and Marcia L. Huber", 
        "id": "Perkins-JCED-2006", 
        "volume": "51", 
        "year": "2006", 
        "owner": "Belli", 
        "type": "article", 
        "pages": "898-904"
    }, 
    "Geller-PURDUE-2000": {
        "title": "Viscosity of Mixed Refrigerants R404A, R407C, R410A, and R507A", 
        "timestamp": "2013.04.08", 
        "booktitle": "2000 International Refrigeration Conferences at Purdue University", 
        "author": "V. Geller", 
        "year": "2000", 
        "owner": "Belli", 
        "type": "conference", 
        "id": "Geller-PURDUE-2000"
    }, 
    "Platzer-BOOK-1990": {
        "publisher": "Springer-Verlag", 
        "author": "B. Platzer and A. Polt and G. Maurer", 
        "timestamp": "2013.05.20", 
        "title": "Thermophysical Properties of Refrigerants", 
        "year": "1990", 
        "owner": "Belli", 
        "type": "book", 
        "id": "Platzer-BOOK-1990"
    }, 
    "Akasaka-DELFT-2013": {
        "title": "A Fundamental Equation of State For Low-GWP Refrigerant HFO-1234ze(Z)", 
        "timestamp": "2013.08.05", 
        "booktitle": "4th IIR Conference on ThermophysicalProperties and Transfer Processes\nof Refrigerants, Delft, The Netherlands, 2013", 
        "author": "Ryo Akasaka and Yukihiro Higashi and Shigeru Koyama", 
        "id": "Akasaka-DELFT-2013", 
        "year": "2013", 
        "owner": "Belli", 
        "type": "conference", 
        "pages": "TP-052"
    }, 
    "Aleksandrov-TE-2011": {
        "title": "Using Fundamental Equations of State for Calculating the Thermodynamic\nProperties of Normal Undecane", 
        "timestamp": "2013.04.11", 
        "journal": "Thermal Engineering", 
        "author": "I. S. Aleksandrov and A. A. Gerasimov and B. A. Grigor'ev", 
        "number": "8", 
        "id": "Aleksandrov-TE-2011", 
        "volume": "58", 
        "year": "2011", 
        "owner": "Belli", 
        "type": "article", 
        "pages": "691-698"
    }, 
    "Huber-JPCRD-2009": {
        "title": "New International Formulation for the Viscosity of H2O", 
        "timestamp": "2013.04.08", 
        "journal": "J. Phys. Chem. Ref. Data", 
        "author": "M.L. Huber and R.A. Perkins and A. Laesecke and D.G. Friend and J.V.\nSengers and M.J Assael and I.M. Metaxa and E. Vogel and R. Mare{\\v\ns} and K. Miyagawa", 
        "number": "2", 
        "id": "Huber-JPCRD-2009", 
        "volume": "38", 
        "year": "2009", 
        "owner": "Belli", 
        "type": "article", 
        "pages": "101-125"
    }, 
    "Rui-FPE-2013": {
        "comment": "Erratum in paper: a1 should be -17.5983849 and a2 should be 8.87150449", 
        "title": "An equation of state for the thermodynamic properties of 1,1,1,2,3,3-hexafluoropropane\n(R236ea)", 
        "timestamp": "2013.04.10", 
        "journal": "Fluid Phase Equilibria", 
        "author": "Xinfang Rui and Jiang Pan and Yugang Wang", 
        "id": "Rui-FPE-2013", 
        "volume": "341", 
        "year": "2013", 
        "owner": "Belli", 
        "type": "article", 
        "pages": "78-85"
    }, 
    "Arp-NIST-1998": {
        "title": "Thermophysical Properties of Helium-4 from 0.8 to 1500 K with Pressures\nto 2000 MPa - NIST Technical Note 1334 (revised)", 
        "timestamp": "2013.08.05", 
        "author": "V.D. Arp and R.D. McCarty and D.G Friend", 
        "id": "Arp-NIST-1998", 
        "year": "1998", 
        "owner": "Belli", 
        "type": "techreport", 
        "institution": "NIST"
    }, 
    "Richardson-JPCRD-2013": {
        "title": "Fundamental Equation of State for Deuterium", 
        "timestamp": "2013.07.28", 
        "journal": "J. Phys. Chem Ref. Data", 
        "author": "I.A. Richardson and J.W. Leachman and E.W. Lemmon", 
        "volume": "In Press", 
        "year": "2013", 
        "owner": "Belli", 
        "type": "article", 
        "id": "Richardson-JPCRD-2013"
    }, 
    "Wu-IJT-2012": {
        "doi": "10.1007/s10765-011-1151-3", 
        "title": "An Equation of State for Fluoroethane (R161)", 
        "timestamp": "2014.01.22", 
        "journal": "Int J Thermophys", 
        "author": "Jiangtao Wu and Yong Zhou", 
        "id": "Wu-IJT-2012", 
        "volume": "33", 
        "year": "2012", 
        "owner": "Belli", 
        "type": "article", 
        "pages": "220-234"
    }, 
    "Chichester-NIST-2008": {
        "title": "NISTIR 6650: Documentation and Assessment of the Transport Property\nModel for Mixtures Implemented in NIST REFPROP (Version 8.0)", 
        "timestamp": "2013.04.08", 
        "author": "Justin C. Chichester and Marcia L. Huber", 
        "id": "Chichester-NIST-2008", 
        "year": "June 2008", 
        "owner": "Belli", 
        "type": "techreport", 
        "institution": "National Institute of Standards and Technology (NIST)"
    }, 
    "Wu-JPCRD-2011": {
        "title": "An Equation of State for the Thermodynamic Properties of Dimethyl\nEther", 
        "timestamp": "2013.04.09", 
        "journal": "J. Phys. Chem. Ref. Data", 
        "author": "Jiangtao Wu and Yong Zhou and Eric W. Lemmon", 
        "number": "2", 
        "id": "Wu-JPCRD-2011", 
        "volume": "40", 
        "year": "2011", 
        "owner": "Belli", 
        "type": "article", 
        "pages": "023104-1:16"
    }, 
    "Huber-IECR-2006": {
        "title": "Correlation for the Viscosity of Pentafluoroethane (R125) from the\nTriple Point to 500 K at Pressures up to 60 MPa", 
        "timestamp": "2013.04.13", 
        "journal": "Ind. Eng. Chem. Res.", 
        "author": "Marcia L. Huber and Arno Laesecke", 
        "id": "Huber-IECR-2006", 
        "volume": "45", 
        "year": "2006", 
        "owner": "Belli", 
        "type": "article", 
        "pages": "4447-4453"
    }, 
    "Tanaka-IJT-1996": {
        "title": "Thermal Conductivity and Viscosity of 2,2-Dichloro-1,1,1-Trifluoroethane\n(HCFC-123)", 
        "timestamp": "2013.04.13", 
        "journal": "International Journal of Thermophysics", 
        "author": "Y. Tanaka and T. Sotani", 
        "number": "2", 
        "id": "Tanaka-IJT-1996", 
        "volume": "17", 
        "year": "1996", 
        "owner": "Belli", 
        "type": "article", 
        "pages": "293-328"
    }, 
    "Huber-FPE-2005": {
        "title": "Thermal conductivity correlations for minor constituent fluids in\nnatural gas: n-octane, n-nonane and n-decane", 
        "timestamp": "2013.04.14", 
        "journal": "Fluid Phase Equilibria", 
        "author": "M.L. Huber and R.A. Perkins", 
        "id": "Huber-FPE-2005", 
        "volume": "227", 
        "year": "2005", 
        "owner": "Belli", 
        "type": "article", 
        "pages": "47-55"
    }, 
    "Huber-FPE-2004": {
        "title": "Viscosity correlations for minor constituent fluids in natural gas:\nn-octane, n-nonane and n-decane", 
        "timestamp": "2013.04.14", 
        "journal": "Fluid Phase Equilibria", 
        "author": "Marcia L. Huber and Arno Laesecke and Hong Wei Xiang", 
        "id": "Huber-FPE-2004", 
        "volume": "224", 
        "year": "2004", 
        "owner": "Belli", 
        "type": "article", 
        "pages": "263-270"
    }, 
    "Huber-IECR-2003": {
        "title": "Model for the Viscosity and Thermal Conductivity of Refrigerants, Including a New Correlation for the Viscosity of R134a", 
        "timestamp": "2010.07.06", 
        "journal": "Ind. Eng. Chem. Res.", 
        "author": "Marcia L. Huber and Arno Laesecke and Richard A. Perkins", 
        "id": "Huber-IECR-2003", 
        "volume": "42", 
        "year": "2003", 
        "owner": "ibell", 
        "type": "article", 
        "pages": "3163-3178"
    }, 
    "Penoncello-IJT-1995": {
        "title": "A Thermodynamic Property Formulation for Cyclohexane", 
        "timestamp": "2013.04.08", 
        "journal": "Int. J. Thermophys.", 
        "author": "S. G. Penoncello and R. T Jacobsen and A. R. H. Goodwin", 
        "number": "2", 
        "id": "Penoncello-IJT-1995", 
        "volume": "16", 
        "year": "1995", 
        "owner": "Belli", 
        "type": "article", 
        "pages": "519-531"
    }, 
    "Smukala-JPCRD-2000": {
        "title": "New Equation of State for Ethylene Covering the Fluid Region for\nTemperatures From the Melting Line to 450 K at Pressures up to 300\nMPa", 
        "timestamp": "2013.04.08", 
        "journal": "J. Phys. Chem. Ref. Data", 
        "author": "J. Smukala and R. Span and W. Wagner", 
        "number": "5", 
        "id": "Smukala-JPCRD-2000", 
        "volume": "29", 
        "year": "2000", 
        "owner": "Belli", 
        "type": "article", 
        "pages": "1053-1121"
    }, 
    "Therminol2007": {
        "title": "Therminol Heat Transfer Reference Disk, Version 5.0", 
        "type": "misc", 
        "id": "Therminol2007", 
        "author": "Eastman Chemical Company"
    }, 
    "Perkins-JCED-2011": {
        "title": "Measurement and Correlation of the Thermal Conductivity of 2,3,3,3-Tetrafluoroprop-1-ene\n(R1234yf) and trans-1,3,3,3-Tetrafluoropropene (R1234ze(E))", 
        "timestamp": "2013.04.09", 
        "journal": "Journal of Chemical Engineering Data", 
        "author": "Richard A. Perkins and Marcia L. Huber", 
        "id": "Perkins-JCED-2011", 
        "volume": "56", 
        "year": "2011", 
        "owner": "Belli", 
        "type": "article", 
        "pages": "4868-4874"
    }, 
    "McLinden-PREPRINT-2013": {
        "title": "Thermodynamic Properties of R-227ea, R-365mfc, R-115, and R-13I1", 
        "timestamp": "2013.04.09", 
        "journal": "J. Chem. Eng. Data", 
        "author": "M.O. McLinden and E.W. Lemmon", 
        "year": "To be submitted", 
        "owner": "Belli", 
        "type": "article", 
        "id": "McLinden-PREPRINT-2013"
    }, 
    "OrtizVega-2010": {
        "title": "Equation of state for Helium", 
        "timestamp": "2013.08.05", 
        "author": "D.O. Ortiz-Vega and K.R. Hall and V.D. Arp and E.W. Lemmon", 
        "note": "Unpublished - coefficients from REPROP with permission", 
        "year": "2013", 
        "owner": "Belli", 
        "type": "unpublished", 
        "id": "OrtizVega-2010"
    }, 
    "Lemmon-JPCRD-2000": {
        "keyword": "EOS", 
        "title": "Thermodynamic Properties of Air and Mixtures of Nitrogen, Argon, and Oxygen from 60 to 2000 K at Pressures to 2000 MPa", 
        "timestamp": "2013.04.08", 
        "journal": "J. Phys. Chem. Ref. Data", 
        "author": "Eric Lemmon and Richard T. Jacobsen and Steven G. Penoncello and\nDaniel Friend", 
        "number": "3", 
        "id": "Lemmon-JPCRD-2000", 
        "volume": "29", 
        "file": ":D\\:\\\\My_Documents\\\\Library\\\\Papers\\\\Lemmon 2000.pdf:PDF", 
        "year": "2000", 
        "owner": "Belli", 
        "type": "article", 
        "pages": "331-385"
    }, 
    "Jacobsen-FPE-1992": {
        "title": "A Fundamental Equation for Trichlorofluoromethane (R-11)", 
        "timestamp": "2013.04.10", 
        "journal": "Fluid Phase Equilibria", 
        "author": "R.T Jacobsen and S.G. Penoncello and E.W. Lemmon", 
        "id": "Jacobsen-FPE-1992", 
        "volume": "80", 
        "year": "1992", 
        "owner": "Belli", 
        "type": "article", 
        "pages": "45-56"
    }, 
    "Holland-JPCRD-1983": {
        "title": "A Correlation of the Viscosity and Thermal Conductivity Data of\nGaseous and Liquid Ethylene", 
        "timestamp": "2013.04.08", 
        "journal": "J. Phys. Chem. Ref. Data", 
        "author": "P.M. Holland and B.E. Eaton and H.J.M. Hanley", 
        "number": "4", 
        "id": "Holland-JPCRD-1983", 
        "volume": "12", 
        "year": "1983", 
        "owner": "Belli", 
        "type": "article", 
        "pages": "917-932"
    }, 
    "Muzny-JCED-2013": {
        "title": "Correlation for the Viscosity of Normal Hydrogen Obtained from Symbolic\nRegression", 
        "timestamp": "2013.04.10", 
        "journal": "J. Chem. Eng. Data", 
        "author": "Chris D. Muzny and Marcia L. Huber and Andrei F. Kazakov", 
        "year": "2013", 
        "owner": "Belli", 
        "type": "article", 
        "id": "Muzny-JCED-2013"
    }, 
    "Jaeschke-IJT-1995": {
        "title": "Ideal-Gas Thermodynamic Properties for Natural-Gas Applications", 
        "timestamp": "2013.04.08", 
        "journal": "Int. J. Thermophys.", 
        "author": "M. Jaeschke and P. Schley", 
        "number": "6", 
        "id": "Jaeschke-IJT-1995", 
        "volume": "16", 
        "year": "1995", 
        "owner": "Belli", 
        "type": "article", 
        "pages": "1381-1392"
    }, 
    "Fenghour-JPCRD-1995": {
        "note": "5", 
        "title": "The Viscosity of Ammonia", 
        "timestamp": "2013.04.08", 
        "journal": "J. Phys. Chem. Ref. Data", 
        "author": "A. Fenghour and W.A. Wakeham and V. Vesovic and J.T.R. Watson and\nJ. Millat and E. Vogel", 
        "id": "Fenghour-JPCRD-1995", 
        "volume": "24", 
        "year": "1995", 
        "owner": "Belli", 
        "type": "article", 
        "pages": "1649-1667"
    }, 
    "Penoncello-JPCRD-2003": {
        "title": "A Fundamental Equation for Trifluoromethane (R-23)", 
        "timestamp": "2013.04.09", 
        "journal": "J. Phys. Chem. Ref. Data", 
        "author": "Steven G. Penoncello and Eric W. Lemmon and Richard T Jacobsen and\nZhengjun Shan", 
        "number": "4", 
        "id": "Penoncello-JPCRD-2003", 
        "volume": "32", 
        "year": "2003", 
        "owner": "Belli", 
        "type": "article", 
        "pages": "1473-1499"
    }, 
    "Lemmon-IJT-1999": {
        "title": "A Generalized Model for the Thermodynamic Properties of Mixtures", 
        "timestamp": "2013.07.07", 
        "journal": "International Journal of Thermophysics", 
        "author": "E. W. Lemmon and R. T Jacobsen", 
        "number": "3", 
        "id": "Lemmon-IJT-1999", 
        "volume": "20", 
        "year": "1999", 
        "owner": "Belli", 
        "type": "article", 
        "pages": "825-835"
    }, 
    "Span-FPE-2001": {
        "title": "Multiparameter equations of state - recent trends and future challenges", 
        "timestamp": "2013.08.18", 
        "journal": "Fluid Phase Equilibria", 
        "author": "R. Span and W. Wagner and E.W. Lemmon and R.T. Jacobsen", 
        "id": "Span-FPE-2001", 
        "volume": "183-184", 
        "year": "2001", 
        "owner": "Belli", 
        "type": "article", 
        "pages": "1-20"
    }, 
    "Younglove-JPCRD-1994": {
        "title": "An International Standard Equation of State for the Thermodynamic\nProperties of Refrigerant 123 (2,2-Dichloro-1,1,1-Trifluoroethane)", 
        "timestamp": "2013.04.08", 
        "journal": "J. Phys. Chem Ref. Data", 
        "author": "Ben A. Younglove", 
        "number": "5", 
        "id": "Younglove-JPCRD-1994", 
        "volume": "23", 
        "year": "1994", 
        "owner": "Belli", 
        "type": "article", 
        "pages": "731-779"
    }, 
    "Marx-BOOK-1992": {
        "publisher": "VDI Verlag", 
        "author": "Volker Marx and Andreas Pruss and Wolfgang Wagner", 
        "timestamp": "2013.05.20", 
        "title": "Neue Zustandsgleichung f\\\"{u}r R 12, R 22, R 11 und R 113 - Beschreibung\ndes therodynamischen Zustandsverhaltens bei Temperaturen bis 525\nK und Dru\\\"{u}cken bis 200 MPa", 
        "number": "57", 
        "volume": "19", 
        "year": "1992", 
        "owner": "Belli", 
        "type": "book", 
        "id": "Marx-BOOK-1992"
    }, 
    "Piazza-FPE-2011": {
        "title": "An equation of state for acetic acid including the association term\nof SAFT", 
        "timestamp": "2014.02.27", 
        "journal": "Fluid Phase Equilibria", 
        "author": "L. Piazza and R. Span", 
        "id": "Piazza-FPE-2011", 
        "volume": "303", 
        "year": "2011", 
        "owner": "Belli", 
        "type": "article", 
        "pages": "134-149"
    }, 
    "Span-JPCRD-2000": {
        "keyword": "EOS", 
        "title": "A Reference Equation of State for the Thermodynamic Properties of\nNitrogen for Temperatures from 63.151 to 1000 K and Pressures to\n2200 MPa", 
        "timestamp": "2013.04.08", 
        "journal": "J. Phys. Chem. Ref. Data", 
        "author": "Roland Span and Eric W. Lemmon and Richard T. Jacobsen and Wolfgang\nWagner and Akimichi Yokozeki", 
        "id": "Span-JPCRD-2000", 
        "volume": "29", 
        "file": ":D\\:\\\\My_Documents\\\\Library\\\\Papers\\\\Span Lemmon et al 2000.pdf:PDF", 
        "year": "2000", 
        "owner": "Belli", 
        "type": "article", 
        "pages": "1361-1433"
    }, 
    "Tufeu-BBPC-1984": {
        "title": "Thermal Conductivity of Ammonia in a Large Temperature and Pressure\nRange Including the Critical Region", 
        "timestamp": "2013.04.08", 
        "journal": "Bereicht der Bunsengesellschaft Phys. Chem.", 
        "author": "R. Tufeu and D.Y. Ivanov and Y. Garrabos and B. Le Neindre", 
        "id": "Tufeu-BBPC-1984", 
        "volume": "88", 
        "year": "1984", 
        "owner": "Belli", 
        "type": "article", 
        "pages": "422-427"
    }, 
    "Marsh-JCED-2002": {
        "title": "Measurement and Correlation of the Thermal Conductivity of Propane\nfrom 86 K to 600 K at Pressures to 70 MPa", 
        "timestamp": "2013.04.08", 
        "journal": "J. Chem. Eng. Data", 
        "author": "Kenneth N. Marsh and Richard A. Perkins and Maria L. V. Ramires", 
        "id": "Marsh-JCED-2002", 
        "volume": "47", 
        "year": "2002", 
        "owner": "Belli", 
        "type": "article", 
        "pages": "932-940"
    }
}